export const NEW_USER_MUTATION = 'NEW_USER';
export const SET_USERS_MUTATION = 'SET_USERS';
export const INFO_MESSAGE_MUTATION = 'INFO_MESSAGE';
export const GET_USEREDIT_MUTATION = 'GET_USEREDIT';
export const DELETE_USERS_MUTATION = 'DELETE_USERS';