export const GET_USERS_ACTION = 'GET_USERS';
export const ADD_USER_ACTION = 'ADD_USER';
export const SEND_MESSAGE_ACTION = 'SEND_MESSAGE';
export const GET_USERBYID_ACTION = 'GET_USERBYID';
export const SAVE_EDITION_ACTION = 'SAVE_EDITION';
export const DELETE_USER_ACTION = 'DELETE_USER';
export const LOGIN_USER_ACTION = 'LOGIN_USER_ACTION';
